theme: jekyll-theme-minimal

title: "MLP-LLM 2025"
description: "Medical Language Processing in the era of Large Language Models"
logo: assets/img/V2_logo.png
author:
  name: Aman Sinha
  url:  http://atilf-umr7118.github.io/MLPLLM2025/

venue: Colocated with CORIA-TALN, Marseille, France
date: 30 juin 2025

children:
  - author-instructions

github: false
