theme: jekyll-theme-minimal

title: "MLP-LLM 2025"
description: "Medical Language Processing in the era of Large Language Models"
logo: assets/img/ATILF_logo.jpg
author:
  name: Aman Sinha
  url:  http://atilf-umr7118.github.io/MLPLLM2025/

organizers:
  - Ioana Buhnila
  - Aman Sinha

github: false
